# Generated by Django 5.1.6 on 2025-03-06 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpay', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='razorpay_order_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
